services:
  mp-fsm:
    image: amsterdam/mp-fsm
    build:
      context: .
      dockerfile: Containerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.13}
    volumes:
      - ".:/app"
